### ISSUE TITLE
Missing bossac tool on linux

### ISSUE THREAD

**Issue by charronguy** [LynnL4/ambd_flash_tool#1]
I am using Manjaro Linux and I can't flash arduino with your program because of the following error:
sh: line 1: /home/guill/Arduino/ambd_flash_tool/tool/linux/bossac: No such file or directory
Thanks if you can fix that.

**Comment by LynnL4** [comment]
**I've put the latest version in the dev branch for now, nd will merge it to master after testing it with no problems.**
refer here https://github.com/LynnL4/ambd_flash_tool/commit/005c22bb5cfdd0f9ec29388eeafda6c72885d767.
